pub const AIM_SPEED: f32 = 10.;
pub const CROSSHAIR_DISTANCE_FROM_PLAYER: f32 = 70.;
pub const MISSILE_POWER_VELOCITY: f32 = 0.25;
pub const MISSILE_MASS: f32 = 25.;
pub const MISSILE_POWER_VELOCITY_MAX_MULTIPLIER: f32 = 25.;
pub const MIN_ENEMY_PIXELS_FROM_PLAYER: f32 = 30.;